// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.WellboreDdms;

/// <summary>
/// Response for bulk data statistics and its meta-data
/// </summary>
public class BulkDataStatisticsResponse
{
    [Required]
    [JsonPropertyName("computationStartDatetime")]
    [JsonConverter(typeof(NullableDateTimeOffsetConverter))]
    public required DateTimeOffset ComputationStartDatetime { get; set; }

    [Required]
    [JsonPropertyName("recordId")]
    public required string RecordId { get; set; }

    [Required]
    [JsonPropertyName("recordVersion")]
    public required long RecordVersion { get; set; }

    /// <summary>
    /// Status available for computation of bulk data statistics
    /// </summary>
    [Required]
    [JsonPropertyName("computationStatus")]
    public required BulkStatisticsStatus ComputationStatus { get; set; }

    [Required]
    [JsonPropertyName("data")]
    public required Dictionary<string, CurveStatistics> Data { get; set; }

}
