// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.WellboreDdms;

public class CatalogRecord
{
    [Required]
    [JsonPropertyName("acl")]
    public required StorageAcl Acl { get; set; }

    [Required]
    [JsonPropertyName("legal")]
    public required Legal Legal { get; set; }

    [Required]
    [JsonPropertyName("data")]
    public required Catalog Data { get; set; }

}
