// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.WellboreDdms;

public class CurveStatistics
{
    [Required]
    [JsonPropertyName("mean")]
    public required string Mean { get; set; }

    [Required]
    [JsonPropertyName("std")]
    public required string Std { get; set; }

    [Required]
    [JsonPropertyName("min")]
    public required string Min { get; set; }

    [Required]
    [JsonPropertyName("10%")]
    public required string _10 { get; set; }

    [Required]
    [JsonPropertyName("50%")]
    public required string _50 { get; set; }

    [Required]
    [JsonPropertyName("90%")]
    public required string _90 { get; set; }

    [Required]
    [JsonPropertyName("max")]
    public required string Max { get; set; }

    [Required]
    [JsonPropertyName("totalCount")]
    public required string TotalCount { get; set; }

    [Required]
    [JsonPropertyName("nonAbsentValuesCount")]
    public required string NonAbsentValuesCount { get; set; }

}
