// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.WellboreDdms;

public class DataframeBasicDescribe
{
    [Required]
    [JsonPropertyName("rowCount")]
    public required long RowCount { get; set; }

    [Required]
    [JsonPropertyName("columnCount")]
    public required long ColumnCount { get; set; }

    /// <summary>
    /// list of column. May be truncated if too many columns, then contains the firsts and lasts once
    /// </summary>
    [Required]
    [JsonPropertyName("columns")]
    public required List<string> Columns { get; set; }

    [Required]
    [JsonPropertyName("indexStart")]
    public required string IndexStart { get; set; }

    [Required]
    [JsonPropertyName("indexEnd")]
    public required string IndexEnd { get; set; }

    [Required]
    [JsonPropertyName("indexType")]
    public required string IndexType { get; set; }

}
