// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Storage;

public class DeleteRecordsException
{
    [JsonPropertyName("cause")]
    public DeleteRecordsException_Cause? Cause { get; set; }

    [JsonPropertyName("stackTrace")]
    public List<DeleteRecordsException_StackTrace>? StackTrace { get; set; }

    [JsonPropertyName("notDeletedRecords")]
    public List<PairStringString>? NotDeletedRecords { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("suppressed")]
    public List<DeleteRecordsException_Suppressed>? Suppressed { get; set; }

    [JsonPropertyName("localizedMessage")]
    public string? LocalizedMessage { get; set; }

}

public class DeleteRecordsException_Cause
{
    [JsonPropertyName("stackTrace")]
    public List<DeleteRecordsException_CauseStackTrace>? StackTrace { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("suppressed")]
    public List<DeleteRecordsException_CauseSuppressed>? Suppressed { get; set; }

    [JsonPropertyName("localizedMessage")]
    public string? LocalizedMessage { get; set; }

}

public class DeleteRecordsException_CauseStackTrace
{
    [JsonPropertyName("classLoaderName")]
    public string? ClassLoaderName { get; set; }

    [JsonPropertyName("moduleName")]
    public string? ModuleName { get; set; }

    [JsonPropertyName("moduleVersion")]
    public string? ModuleVersion { get; set; }

    [JsonPropertyName("methodName")]
    public string? MethodName { get; set; }

    [JsonPropertyName("fileName")]
    public string? FileName { get; set; }

    [JsonPropertyName("lineNumber")]
    public int? LineNumber { get; set; }

    [JsonPropertyName("nativeMethod")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? NativeMethod { get; set; }

    [JsonPropertyName("className")]
    public string? ClassName { get; set; }

}

public class DeleteRecordsException_CauseSuppressed
{
    [JsonPropertyName("stackTrace")]
    public List<DeleteRecordsException_CauseSuppressedStackTrace>? StackTrace { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("localizedMessage")]
    public string? LocalizedMessage { get; set; }

}

public class DeleteRecordsException_CauseSuppressedStackTrace
{
    [JsonPropertyName("classLoaderName")]
    public string? ClassLoaderName { get; set; }

    [JsonPropertyName("moduleName")]
    public string? ModuleName { get; set; }

    [JsonPropertyName("moduleVersion")]
    public string? ModuleVersion { get; set; }

    [JsonPropertyName("methodName")]
    public string? MethodName { get; set; }

    [JsonPropertyName("fileName")]
    public string? FileName { get; set; }

    [JsonPropertyName("lineNumber")]
    public int? LineNumber { get; set; }

    [JsonPropertyName("nativeMethod")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? NativeMethod { get; set; }

    [JsonPropertyName("className")]
    public string? ClassName { get; set; }

}

public class DeleteRecordsException_StackTrace
{
    [JsonPropertyName("classLoaderName")]
    public string? ClassLoaderName { get; set; }

    [JsonPropertyName("moduleName")]
    public string? ModuleName { get; set; }

    [JsonPropertyName("moduleVersion")]
    public string? ModuleVersion { get; set; }

    [JsonPropertyName("methodName")]
    public string? MethodName { get; set; }

    [JsonPropertyName("fileName")]
    public string? FileName { get; set; }

    [JsonPropertyName("lineNumber")]
    public int? LineNumber { get; set; }

    [JsonPropertyName("nativeMethod")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? NativeMethod { get; set; }

    [JsonPropertyName("className")]
    public string? ClassName { get; set; }

}

public class DeleteRecordsException_Suppressed
{
    [JsonPropertyName("stackTrace")]
    public List<DeleteRecordsException_SuppressedStackTrace>? StackTrace { get; set; }

    [JsonPropertyName("message")]
    public string? Message { get; set; }

    [JsonPropertyName("localizedMessage")]
    public string? LocalizedMessage { get; set; }

}

public class DeleteRecordsException_SuppressedStackTrace
{
    [JsonPropertyName("classLoaderName")]
    public string? ClassLoaderName { get; set; }

    [JsonPropertyName("moduleName")]
    public string? ModuleName { get; set; }

    [JsonPropertyName("moduleVersion")]
    public string? ModuleVersion { get; set; }

    [JsonPropertyName("methodName")]
    public string? MethodName { get; set; }

    [JsonPropertyName("fileName")]
    public string? FileName { get; set; }

    [JsonPropertyName("lineNumber")]
    public int? LineNumber { get; set; }

    [JsonPropertyName("nativeMethod")]
    [JsonConverter(typeof(BooleanConverter))]
    public bool? NativeMethod { get; set; }

    [JsonPropertyName("className")]
    public string? ClassName { get; set; }

}
