// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Storage;

/// <summary>
/// A single JSON Patch operation for updating record metadata fields.
/// </summary>
public class PatchOperation
{
    /// <summary>
    /// Bulk update record operation.
    /// </summary>
    [Required]
    [JsonPropertyName("op")]
    public required string Op { get; set; }

    /// <summary>
    /// Bulk update record path.
    /// </summary>
    [Required]
    [JsonPropertyName("path")]
    public required string Path { get; set; }

    /// <summary>
    /// Bulk update record value(s).
    /// </summary>
    [Required]
    [MinLength(1)]
    [JsonPropertyName("value")]
    public required List<string> Value { get; set; }

}
