// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Apis.Schema;

/// <summary>
/// Schema authority source and type description
/// </summary>
public class SchemaIdentity
{
    /// <summary>
    /// Entity authority
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+$")]
    [JsonPropertyName("authority")]
    public required string Authority { get; set; }

    /// <summary>
    /// Entity source
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+$")]
    [JsonPropertyName("source")]
    public required string Source { get; set; }

    /// <summary>
    /// EntityType Code
    /// </summary>
    [Required]
    [RegularExpression(@"^[\w\-\.]+$")]
    [JsonPropertyName("entityType")]
    public required string EntityType { get; set; }

    /// <summary>
    /// Major Schema Version Number
    /// </summary>
    [Required]
    [JsonPropertyName("schemaVersionMajor")]
    public required long SchemaVersionMajor { get; set; }

    /// <summary>
    /// Minor Schema Version Number
    /// </summary>
    [Required]
    [JsonPropertyName("schemaVersionMinor")]
    public required long SchemaVersionMinor { get; set; }

    /// <summary>
    /// Patch Schema Version Number
    /// </summary>
    [Required]
    [JsonPropertyName("schemaVersionPatch")]
    public required long SchemaVersionPatch { get; set; }

    /// <summary>
    /// A read-only system defined id used for referencing of a schema.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

}
