// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Data.Abstract;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractGeoPoliticalContext_1_0_0), "AbstractGeoPoliticalContext.1.0.0.json")]
[JsonDerivedType(typeof(AbstractGeoBasinContext_1_0_0), "AbstractGeoBasinContext.1.0.0.json")]
[JsonDerivedType(typeof(AbstractGeoFieldContext_1_0_0), "AbstractGeoFieldContext.1.0.0.json")]
[JsonDerivedType(typeof(AbstractGeoPlayContext_1_0_0), "AbstractGeoPlayContext.1.0.0.json")]
[JsonDerivedType(typeof(AbstractGeoProspectContext_1_0_0), "AbstractGeoProspectContext.1.0.0.json")]
public class AbstractGeoContext_1_0_0
{
}
