// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Data.Abstract;

/// <summary>
/// A schema like GeoJSON FeatureCollection with a non-WGS 84 CRS context; based on https://geojson.org/schema/FeatureCollection.json. Attention: the coordinate order is fixed: Longitude/Easting/Westing/X first, followed by Latitude/Northing/Southing/Y, optionally height as third coordinate.
/// </summary>
public class AbstractAnyCrsFeatureCollection_1_0_0
{
    [Required]
    [JsonPropertyName("type")]
    public required AbstractAnyCrsFeatureCollection_1_0_0_Type Type { get; set; }

    /// <summary>
    /// The CRS reference into the CoordinateReferenceSystem catalog.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CoordinateReferenceSystemID")]
    public string? CoordinateReferenceSystemID { get; set; }

    /// <summary>
    /// The explicit VerticalCRS reference into the CoordinateReferenceSystem catalog. This property stays empty for 2D geometries. Absent or empty values for 3D geometries mean the context may be provided by a CompoundCRS in 'CoordinateReferenceSystemID' or implicitly EPSG:5714 MSL height
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalCoordinateReferenceSystemID")]
    public string? VerticalCoordinateReferenceSystemID { get; set; }

    /// <summary>
    /// The CRS reference as persistableReference string. If populated, the CoordinateReferenceSystemID takes precedence.
    /// </summary>
    [Required]
    [JsonPropertyName("persistableReferenceCrs")]
    public required string PersistableReferenceCrs { get; set; }

    /// <summary>
    /// The VerticalCRS reference as persistableReference string. If populated, the VerticalCoordinateReferenceSystemID takes precedence. The property is null or empty for 2D geometries. For 3D geometries and absent or null persistableReferenceVerticalCrs the vertical CRS is either provided via persistableReferenceCrs's CompoundCRS or it is implicitly defined as EPSG:5714 MSL height.
    /// </summary>
    [JsonPropertyName("persistableReferenceVerticalCrs")]
    public string? PersistableReferenceVerticalCrs { get; set; }

    /// <summary>
    /// The unit of measure for the Z-axis (only for 3-dimensional coordinates, where the CRS does not describe the vertical unit). Note that the direction is upwards positive, i.e. Z means height.
    /// </summary>
    [JsonPropertyName("persistableReferenceUnitZ")]
    public string? PersistableReferenceUnitZ { get; set; }

    [Required]
    [JsonPropertyName("features")]
    public required List<AbstractAnyCrsFeatureCollection_1_0_0_Features> Features { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractAnyCrsFeatureCollection_1_0_0_Type
{
    [JsonStringEnumMemberName("AnyCrsFeatureCollection")]
    AnyCrsFeatureCollection,

}

public class AbstractAnyCrsFeatureCollection_1_0_0_Features
{
    [Required]
    [JsonPropertyName("type")]
    public required AbstractAnyCrsFeatureCollection_1_0_0_FeaturesType Type { get; set; }

    [Required]
    [JsonPropertyName("properties")]
    public required object Properties { get; set; }

    [Required]
    [JsonPropertyName("geometry")]
    public required AbstractAnyCrsFeatureCollection_1_0_0_Geometry Geometry { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractAnyCrsFeatureCollection_1_0_0_FeaturesType
{
    [JsonStringEnumMemberName("AnyCrsFeature")]
    AnyCrsFeature,

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONPoint), "AnyCrsPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONLineString), "AnyCrsLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONPolygon), "AnyCrsPolygon")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONMultiPoint), "AnyCrsMultiPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONMultiLineString), "AnyCrsMultiLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONMultiPolygon), "AnyCrsMultiPolygon")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONGeometryCollection), "AnyCrsGeometryCollection")]
public class AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONPoint : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPoint";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<double> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONLineString : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsLineString";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONPolygon : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONMultiPoint : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPoint";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONMultiLineString : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiLineString";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONMultiPolygon : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<List<double>>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_AnyCrsGeoJSONGeometryCollection : AbstractAnyCrsFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsGeometryCollection";

    [Required]
    [JsonPropertyName("geometries")]
    public required List<AbstractAnyCrsFeatureCollection_1_0_0_Geometries> Geometries { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONPoint), "AnyCrsPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONLineString), "AnyCrsLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONPolygon), "AnyCrsPolygon")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONMultiPoint), "AnyCrsMultiPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONMultiLineString), "AnyCrsMultiLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONMultiPolygon), "AnyCrsMultiPolygon")]
public class AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
}

public class AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONPoint : AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPoint";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<double> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONLineString : AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsLineString";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONPolygon : AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONMultiPoint : AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPoint";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONMultiLineString : AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiLineString";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_0_0_GeometriesAnyCrsGeoJSONMultiPolygon : AbstractAnyCrsFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<List<double>>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}
