// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Data.Abstract;

/// <summary>
/// A schema like GeoJSON FeatureCollection with a non-WGS 84 CRS context; based on https://geojson.org/schema/FeatureCollection.json. Attention: the coordinate order is fixed: Longitude/Easting/Westing/X first, followed by Latitude/Northing/Southing/Y, optionally height as third coordinate.
/// </summary>
public class AbstractAnyCrsFeatureCollection_1_1_0
{
    [Required]
    [JsonPropertyName("type")]
    public required AbstractAnyCrsFeatureCollection_1_1_0_Type Type { get; set; }

    /// <summary>
    /// The CRS reference into the CoordinateReferenceSystem catalog.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("CoordinateReferenceSystemID")]
    public string? CoordinateReferenceSystemID { get; set; }

    /// <summary>
    /// The explicit VerticalCRS reference into the CoordinateReferenceSystem catalog. This property stays empty for 2D geometries. Absent or empty values for 3D geometries mean the context may be provided by a CompoundCRS in 'CoordinateReferenceSystemID' or implicitly EPSG:5714 MSL height
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-CoordinateReferenceSystem:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalCoordinateReferenceSystemID")]
    public string? VerticalCoordinateReferenceSystemID { get; set; }

    /// <summary>
    /// The explicit vertical unit ID, referring to a reference-data--UnitOfMeasure record; this is only required for features containing 3-dimensional coordinates and undefined vertical CoordinateReferenceSystems; if a VerticalCoordinateReferenceSystemID is populated, the VerticalUnitID is given by the VerticalCoordinateReferenceSystemID's data.CoordinateSystem.VerticalAxisUnitID. The VerticalUnitID definition overrides any self-contained definition in persistableReferenceUnitZ.
    /// </summary>
    [RegularExpression(@"^[\w\-\.]+:reference-data\-\-UnitOfMeasure:[\w\-\.\:\%]+:[0-9]*$")]
    [JsonPropertyName("VerticalUnitID")]
    public string? VerticalUnitID { get; set; }

    /// <summary>
    /// The CRS reference as persistableReference string. If populated, the CoordinateReferenceSystemID takes precedence.
    /// </summary>
    [Required]
    [JsonPropertyName("persistableReferenceCrs")]
    public required string PersistableReferenceCrs { get; set; }

    /// <summary>
    /// The VerticalCRS reference as persistableReference string. If populated, the VerticalCoordinateReferenceSystemID takes precedence. The property is null or empty for 2D geometries. For 3D geometries and absent or null persistableReferenceVerticalCrs the vertical CRS is either provided via persistableReferenceCrs's CompoundCRS or it is implicitly defined as EPSG:5714 MSL height.
    /// </summary>
    [JsonPropertyName("persistableReferenceVerticalCrs")]
    public string? PersistableReferenceVerticalCrs { get; set; }

    /// <summary>
    /// The unit of measure for the Z-axis (only for 3-dimensional coordinates, where the CRS does not describe the vertical unit). Note that the direction is upwards positive, i.e. Z means height.
    /// </summary>
    [JsonPropertyName("persistableReferenceUnitZ")]
    public string? PersistableReferenceUnitZ { get; set; }

    [Required]
    [JsonPropertyName("features")]
    public required List<AbstractAnyCrsFeatureCollection_1_1_0_Features> Features { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractAnyCrsFeatureCollection_1_1_0_Type
{
    [JsonStringEnumMemberName("AnyCrsFeatureCollection")]
    AnyCrsFeatureCollection,

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features
{
    [Required]
    [JsonPropertyName("type")]
    public required AbstractAnyCrsFeatureCollection_1_1_0_Features_Type Type { get; set; }

    [Required]
    [JsonPropertyName("properties")]
    public required object Properties { get; set; }

    [Required]
    [JsonPropertyName("geometry")]
    public required AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry Geometry { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractAnyCrsFeatureCollection_1_1_0_Features_Type
{
    [JsonStringEnumMemberName("AnyCrsFeature")]
    AnyCrsFeature,

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONPoint), "AnyCrsPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONLineString), "AnyCrsLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONPolygon), "AnyCrsPolygon")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONMultiPoint), "AnyCrsMultiPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONMultiLineString), "AnyCrsMultiLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONMultiPolygon), "AnyCrsMultiPolygon")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection), "AnyCrsGeometryCollection")]
public class AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONPoint : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPoint";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<double> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONLineString : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsLineString";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONPolygon : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONMultiPoint : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPoint";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONMultiLineString : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiLineString";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONMultiPolygon : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<List<double>>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection : AbstractAnyCrsFeatureCollection_1_1_0_Features_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsGeometryCollection";

    [Required]
    [JsonPropertyName("geometries")]
    public required List<AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries> Geometries { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONPoint), "AnyCrsPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONLineString), "AnyCrsLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONPolygon), "AnyCrsPolygon")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONMultiPoint), "AnyCrsMultiPoint")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONMultiLineString), "AnyCrsMultiLineString")]
[JsonDerivedType(typeof(AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONMultiPolygon), "AnyCrsMultiPolygon")]
public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONPoint : AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPoint";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<double> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONLineString : AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsLineString";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONPolygon : AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONMultiPoint : AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPoint";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONMultiLineString : AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiLineString";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_GeometriesAnyCrsGeoJSONMultiPolygon : AbstractAnyCrsFeatureCollection_1_1_0_Features_GeometryAnyCrsGeoJSONGeometryCollection_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "AnyCrsMultiPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<List<double>>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}
