// ==================================================================================================
// <auto-generated/>
// This code was generated by OSDU Client generator tool. 
// Do not modify it manually as the changes will be overwritten when the code is regenerated.
// ==================================================================================================

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Osdu.Client.Converters;

namespace Osdu.Client.Data.Abstract;

/// <summary>
/// GeoJSON feature collection as originally published in https://geojson.org/schema/FeatureCollection.json. Attention: the coordinate order is fixed: Longitude first, followed by Latitude, optionally height above MSL (EPSG:5714) as third coordinate.
/// </summary>
public class AbstractFeatureCollection_1_0_0
{
    [Required]
    [JsonPropertyName("type")]
    public required AbstractFeatureCollection_1_0_0_Type Type { get; set; }

    [Required]
    [JsonPropertyName("features")]
    public required List<AbstractFeatureCollection_1_0_0_Features> Features { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractFeatureCollection_1_0_0_Type
{
    [JsonStringEnumMemberName("FeatureCollection")]
    FeatureCollection,

}

public class AbstractFeatureCollection_1_0_0_Features
{
    [Required]
    [JsonPropertyName("type")]
    public required AbstractFeatureCollection_1_0_0_FeaturesType Type { get; set; }

    [Required]
    [JsonPropertyName("properties")]
    public required object Properties { get; set; }

    [Required]
    [JsonPropertyName("geometry")]
    public required AbstractFeatureCollection_1_0_0_Geometry Geometry { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum AbstractFeatureCollection_1_0_0_FeaturesType
{
    [JsonStringEnumMemberName("Feature")]
    Feature,

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONPoint), "Point")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONLineString), "LineString")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONPolygon), "Polygon")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONMultiPoint), "MultiPoint")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONMultiLineString), "MultiLineString")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONMultiPolygon), "MultiPolygon")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeoJSONGeometryCollection), "GeometryCollection")]
public class AbstractFeatureCollection_1_0_0_Geometry
{
}

public class AbstractFeatureCollection_1_0_0_GeoJSONPoint : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "Point";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<double> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeoJSONLineString : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "LineString";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeoJSONPolygon : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "Polygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeoJSONMultiPoint : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "MultiPoint";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeoJSONMultiLineString : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "MultiLineString";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeoJSONMultiPolygon : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "MultiPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<List<double>>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeoJSONGeometryCollection : AbstractFeatureCollection_1_0_0_Geometry
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "GeometryCollection";

    [Required]
    [JsonPropertyName("geometries")]
    public required List<AbstractFeatureCollection_1_0_0_Geometries> Geometries { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeometriesGeoJSONPoint), "Point")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeometriesGeoJSONLineString), "LineString")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeometriesGeoJSONPolygon), "Polygon")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeometriesGeoJSONMultiPoint), "MultiPoint")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeometriesGeoJSONMultiLineString), "MultiLineString")]
[JsonDerivedType(typeof(AbstractFeatureCollection_1_0_0_GeometriesGeoJSONMultiPolygon), "MultiPolygon")]
public class AbstractFeatureCollection_1_0_0_Geometries
{
}

public class AbstractFeatureCollection_1_0_0_GeometriesGeoJSONPoint : AbstractFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "Point";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<double> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeometriesGeoJSONLineString : AbstractFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "LineString";

    [Required]
    [MinLength(2)]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeometriesGeoJSONPolygon : AbstractFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "Polygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeometriesGeoJSONMultiPoint : AbstractFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "MultiPoint";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<double>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeometriesGeoJSONMultiLineString : AbstractFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "MultiLineString";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<double>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}

public class AbstractFeatureCollection_1_0_0_GeometriesGeoJSONMultiPolygon : AbstractFeatureCollection_1_0_0_Geometries
{
    /// <summary>
    /// Discriminator property. Value is handled by the JSON serializer's polymorphic
    /// metadata and is not directly serialized/deserialized as a regular property.
    /// </summary>
    [JsonIgnore]
    public string Type { get; set; } = "MultiPolygon";

    [Required]
    [JsonPropertyName("coordinates")]
    public required List<List<List<List<double>>>> Coordinates { get; set; }

    [MinLength(4)]
    [JsonPropertyName("bbox")]
    public List<double>? Bbox { get; set; }

}
