// <auto-generated/>
using System.Text;
using Microsoft.OpenApi;

namespace Osdu.Client.Generator.ConsoleApp.Generators.Schema;

/// <summary>
/// Static utility methods for schema generation (sanitization, XML escaping, etc.).
/// </summary>
public static class SchemaHelpers
{
    public static bool HasFlag(JsonSchemaType type, JsonSchemaType flag)
        => (type & flag) == flag;

    /// <summary>
    /// Returns true if the schema explicitly allows null values.
    /// Handles both OpenAPI 3.0 (nullable: true) and 3.1 (type includes "null").
    /// In Microsoft.OpenApi v3.x, both representations are unified into
    /// JsonSchemaType.Null being present in the Type flags.
    /// </summary>
    public static bool IsExplicitlyNullable(IOpenApiSchema schema)
    {
        // Resolve through $ref to get the actual schema's type information
        var resolved = schema is OpenApiSchemaReference schemaRef
            ? schemaRef.Target
            : schema;

        if (resolved is null)
            return false;

        // If the schema has no explicit type (e.g., allOf/oneOf compositions),
        // it is not explicitly nullable — nullability is not implied by absence of type.
        if (resolved.Type is null)
            return false;

        // OpenAPI 3.0: nullable: true → converted to JsonSchemaType.Null by Microsoft.OpenApi v3.x
        // OpenAPI 3.1: type: ["string", "null"] → JsonSchemaType.Null is present in the flags
        return HasFlag(resolved.Type.Value, JsonSchemaType.Null);
    }

    /// <summary>
    /// Extracts the reference ID (schema name) from a $ref schema, or null if not a reference.
    /// </summary>
    public static string? GetSchemaReferenceName(IOpenApiSchema schema)
        => schema is OpenApiSchemaReference schemaRef ? schemaRef.Reference.Id : null;

    /// <summary>
    /// Patches a generated class's code to add inheritance from the given base class.
    /// If the class already has a base class, the code is left unchanged.
    /// </summary>
    public static string PatchClassInheritance(string code, string className, string baseClassName)
    {
        // Match "public class ClassName" or "public class ClassName : ExistingBase"
        var pattern = $"public class {className}";
        var idx = code.IndexOf(pattern, StringComparison.Ordinal);
        if (idx < 0)
            return code;

        var afterClass = idx + pattern.Length;
        var lineEnd = code.IndexOf('\n', afterClass);
        if (lineEnd < 0) lineEnd = code.Length;

        var remainder = code[afterClass..lineEnd].TrimEnd('\r');

        if (remainder.TrimStart().StartsWith(':'))
        {
            // Already has base class — don't change (it already inherits from something)
            return code;
        }
        else
        {
            // No base class — add one
            return code[..afterClass] + $" : {baseClassName}" + code[afterClass..];
        }
    }

    /// <summary>
    /// Patches a generated class's code to add inheritance and a using statement if needed.
    /// </summary>
    public static string PatchClassInheritanceWithUsing(string code, string className, string baseClassName, string? baseNamespace)
    {
        code = PatchClassInheritance(code, className, baseClassName);

        // Add using for the base class namespace if it's not already present
        if (baseNamespace is not null && !code.Contains($"using {baseNamespace};"))
        {
            // Insert after the last existing using statement
            var lastUsing = code.LastIndexOf("using ", StringComparison.Ordinal);
            if (lastUsing >= 0)
            {
                var endOfLine = code.IndexOf('\n', lastUsing);
                if (endOfLine >= 0)
                {
                    code = code[..(endOfLine + 1)] + $"using {baseNamespace};\n" + code[(endOfLine + 1)..];
                }
            }
        }
    
        return code;
    }

    /// <summary>
    /// Computes a stable cache key for a set of oneOf/anyOf variants based on their $ref names.
    /// Returns null if any variant is not a $ref (inline schemas can't be deduplicated this way).
    /// </summary>
    public static string? GetOneOfSignature(IList<IOpenApiSchema> variants)
    {
        var refs = variants.OfType<OpenApiSchemaReference>().ToList();
        if (refs.Count != variants.Count || refs.Count == 0)
            return null;

        var names = refs.Select(r => r.Reference.Id).OrderBy(n => n, StringComparer.Ordinal);
        return string.Join("|", names);
    }

    public static string Sanitize(string? name)
    {
        if (string.IsNullOrEmpty(name)) return "Unknown";
        var result = new StringBuilder();
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                result.Append(ch);
            else if (ch == '.')
                result.Append('_');
        }
        if (result.Length == 0)
            return "Unknown";
        var sanitized = result.ToString();
        // Remove trailing "_json" suffix (from schema file references like "Schema.1.0.0.json")
        if (sanitized.EndsWith("_json", StringComparison.OrdinalIgnoreCase))
            sanitized = sanitized[..^5];
        // Trim trailing underscores after all replacements
        sanitized = sanitized.TrimEnd('_');
        if (sanitized.Length == 0)
            return "Unknown";
        if (char.IsDigit(sanitized[0]))
            sanitized = "_" + sanitized;
        return sanitized;
    }

    public static string EscapeXml(string text)
        => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    public static void AppendSummary(StringBuilder sb, string? description, string prefix)
    {
        if (description is null) return;

        sb.AppendLine($"{prefix}/// <summary>");
        foreach (var line in description.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries))
        {
            sb.AppendLine($"{prefix}/// {EscapeXml(line.Trim())}");
        }
        sb.AppendLine($"{prefix}/// </summary>");
    }
}
