name: Release Please

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions: {}

jobs:
  release-please:
    name: Release Please
    permissions:
      contents: write # Required to update changelog file
      pull-requests: write # Required to create release PRs
    uses: equinor/ops-actions/.github/workflows/release-please-manifest.yml@7e3b7a3ebdfe8bac700e5714e9bfd6b5b33ed6a9 # v9.41.1

  publish-nuget:
    name: Publish NuGet Package
    needs: release-please
    if: needs.release-please.outputs.releases_created == 'true'
    permissions:
      contents: read # Required to checkout code
      packages: write # Required to publish packages to GitHub Packages
    uses: ./.github/workflows/publish-nuget.yml
    with:
      release-path: ${{ needs.release-please.outputs.paths_released }}
